name = "heroicons"
version = "1.0.0"
licences = ["MIT"]
description = "Port of tailwindlabs/heroicons"
repository = { type = "github", user = "yreynhout", repo = "https://github.com/yreynhout/heroicons" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"
birdie = ">= 1.4.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.2.2 and < 3.0.0"
